### ISSUE TITLE
Also download problem statements?

### ISSUE THREAD

**Issue by pathikrit** [plesiv/hac#3]

**Comment by plesiv** [comment]
`hac` was intended to do narrow range of tasks (as lean as possible); though this might be added, but I don't see it being too useful for wide enough audience, though - and it will for sure complicate maintenance.

I'll address it more in-depth later, since I put active development of `hac` on hold for now.

**Comment by plesiv** [comment]
This issue will be closed unresolved because I don't see requested feature being that critical. Handling problem statement processing could introduce bunch of non-critical logic (e.g. handling images).
